### ISSUE TITLE
“选择文件” 按钮不能点

### ISSUE THREAD

**Issue by Davi-He** [Jieli-Tech/Android-JL_OTA#1]
APP: https://github.com/Jieli-Tech/Android-JL_OTA/tree/master/apk/JLOTA_V1.2.0_release.apk
![Screenshot_20210511_201450_com jieli otasdk](https://user-images.githubusercontent.com/3032425/117813743-08f45180-b296-11eb-87c1-c65c0c2fbdbf.jpg)
手机版本，已经给了存储权限
![Screenshot_20210511_201728_ B@84b796](https://user-images.githubusercontent.com/3032425/117813768-13aee680-b296-11eb-9bc4-4ac49f514965.jpg)

**Comment by zqjasonzhong** [comment]
![image](https://user-images.githubusercontent.com/14267397/125429191-fea28442-1f45-4184-a32d-626dd249f5e9.png)
不是选择文件的，是复制升级文件到对应文件夹，遍历文件夹显示的。具体请看使用说明文档。
