### ISSUE TITLE
OTA升级后无法重连设备，这个该怎么办？

### ISSUE THREAD

**Issue by HuZengKan** [Jieli-Tech/Android-JL_OTA#10]
```
ConfigHelper.Companion.getInstance().setBleWay(false); // 使用demo的apk，BLE无法扫描出设备，SPP可以扫描出设备

manager.getBluetoothOption().setUseReconnect(true);

manager.startOTA(new UpgradeCbHelper() {
   /**
    * 需要回连的回调
    *
    * 注意: 1.仅连接BLE通讯通道
    * 2.用于单备份OTA
    *
    * @param addr 回连设备的MAC地址
    * @param isNewReconnectWay 是否使用新回连方式
    */
  @Override
  public void onNeedReconnect(String addr, boolean isNewReconnectWay) {
    super.onNeedReconnect(addr, isNewReconnectWay);
    LogUtil.i(TAG, "onNeedReconnect : " + isNewReconnectWay + "\t" + addr);
  }
  ...
}
```
每次OTA升级会改变mac地址。
无法触发onNeedReconnect回调（打印不出Log），导致OTA升级后无法重连设备，这个该怎么办？
PS：使用demo的apk也是一样的，OTA升级后改变mac，需要手动重连。

**Comment by HuZengKan** [comment]
```
manager.getBluetoothOption().setUseReconnect(true);
```
补充：已经设置使用重连了

**Comment by zqjasonzhong** [comment]
![image](https://github.com/user-attachments/assets/3bf4d0a2-c18c-4b73-aa7b-faabe1f7a411)
你的配置是自定义回连设备的流程。
onNeedReconnect没有回调，检查下是否 getConnectedDevice是否返回 null。用来判断设备是否连接。
固件升级成功后，mac改变。说明升级文件有问题。
如果固件还没升级，只是在回连设备的流程，mac改变，是正常的。
还有，遇到问题，描述完后，附上对应的打印日志，才好分析问题。

**Comment by zqjasonzhong** [comment]
可以参考下[接入文档](https://doc.zh-jieli.com/Apps/Android/ota/zh-cn/master/development/development_desc.html#id1)

**Comment by Fereshte874** [comment]
抱歉我没说清楚，我这边触发了onStopOTA()所以我以为固件升级成功了，日志也附上，请问这是升级文件的问题吗？
[ota_log_app_20240827180217.382.txt](https://github.com/user-attachments/files/16760378/ota_log_app_20240827180217.382.txt)

**Comment by zqjasonzhong** [comment]
> 抱歉我没说清楚，我这边触发了onStopOTA()所以我以为固件升级成功了，日志也附上，请问这是升级文件的问题吗？ [ota_log_app_20240827180217.382.txt](https://github.com/user-attachments/files/16760378/ota_log_app_20240827180217.382.txt)

看打印日志，升级是成功了的。你的设备是双备份OTA方案，不需要回连设备的。单备份OTA才需要回连。具体可以看看[单备份OTA与双备份OTA的区别](https://doc.zh-jieli.com/Apps/Android/ota/zh-cn/master/other/qa.html#otaota)
如果设备的地址改变，就是升级文件有问题了，你可以问问提供你升级文件的同事。应该是设置了清除VM之类的配置。
还有，初始化成功后，调用``startOTA``, 收到``onStopOTA``回调，就是**升级成功**了。
