### ISSUE TITLE
android apk是否可以用于升级程序

### ISSUE THREAD

**Issue by alittleray** [Jieli-Tech/Android-JL_OTA#2]
你好，板子上用的AC6925B，想用这个项目里面的android apk升级设备程序，是否可行。
烧写标准sdk程序，设备连接连搜不到设备，你们既然做了这种配套功能，可否把文档写的好一点

**Comment by zqjasonzhong** [comment]
标准的SDK，可以用这个项目的OTA库实现。但是不能用我司demo的包名。关于文档有什么疑问，可以加入我司开源群(钉钉: AC63/69杰理开源社区)咨询。
