### ISSUE TITLE
Execution failed for task ‘:app:kaptDebugKotlin‘或Execution failed for task ‘:app:kaptReleaseKotlin‘

### ISSUE THREAD

**Issue by xxfenxx** [Jieli-Tech/Android-JL_OTA#5]
最新版本Android studio 工程运行报错

Execution failed for task ‘:app:kaptDebugKotlin‘ 或 Execution failed for task ‘:app:kaptReleaseKotlin‘

报错原因是运行环境所导致？如果是请说明一下需要的环境配置

**Comment by zqjasonzhong** [comment]
这种情况大概率是你编译环境配置有问题导致的。你可以把编译环境修改到你当前的使用的编译环境。
插件Gradle升级到合适的版本。
JDK环境需要检查，如果是7.0.0以上的，修改为JDK11+。
具体配置编译环境的问题，可以网上搜索解决方案。

**Comment by xxfenxx** [comment]
谢谢你的来信，有有空常联系哦！

**Comment by xxfenxx** [comment]
谢谢你的来信，有有空常联系哦！
