### ISSUE TITLE
引入对应的包，出现了设备认证失败，无法进行ota

### ISSUE THREAD

**Issue by themores** [Jieli-Tech/Android-JL_OTA#6]
能否留下钉钉群，加进去问一下问题

**Comment by zqjasonzhong** [comment]
请看在线文档的开源社区：https://doc.zh-jieli.com/Apps/Android/ota/zh-cn/master/other/feedback.html

**Comment by zqjasonzhong** [comment]
在线文档链接：https://doc.zh-jieli.com/Apps/Android/ota/zh-cn/master/index.html

**Comment by themores** [comment]
貌似没搜到啊，钉钉...31697748

**Comment by zqjasonzhong** [comment]
> 
试试搜索，钉钉群  3375034077

**Comment by themores** [comment]
拒绝了，。。。未给通过，
能不能拉一下

**Comment by themores** [comment]
怎么回事，全部拒绝？

**Comment by themores** [comment]
![image](https://github.com/Jieli-Tech/Android-JL_OTA/assets/26290632/6d3001ee-44c0-43ad-9c91-a0836b08f612)

**Comment by themores** [comment]
帮忙看下这个情况...

**Comment by zqjasonzhong** [comment]
> 帮忙看下这个情况...

看打印是设备在20秒内都没有请求升级数据，导致SDK超时退出OTA流程。找下设备端看看

**Comment by themores** [comment]
我这边是采购你家的蓝牙芯片， 然后我这边是客户端，需要集成你们的ota ，你们这边群审核很难通过啊，自己集成真的很多问题....😌，浪费时间，用户又要各种退货。

**Comment by zqjasonzhong** [comment]
> 我这边是采购你家的蓝牙芯片， 然后我这边是客户端，需要集成你们的ota ，你们这边群审核很难通过啊，自己集成真的很多问题....😌，浪费时间，用户又要各种退货。

关于技术支持，你们可以向我们深圳办的客服，申请技术支持。我司审批后，会组建对应的讨论组，帮忙解决问题的。
如果还没有加入讨论组，可以在issues提问。
第一、用"杰理OTA”软件测试固件SDK的OTA功能是否正常。
第二、参考[在线开发文档](https://doc.zh-jieli.com/Apps/Android/ota/zh-cn/master/index.html)和demo接入到你们的工程
第三、如果遇到问题，请保持打印日志，并上传。描述好问题情况和发生时间段。详情请参考[调试说明](https://doc.zh-jieli.com/Apps/Android/ota/zh-cn/master/other/debug.html)

**Comment by themores** [comment]
把你们demo 里面的代码全部copy 到项目了，几个工具类。OK了.....
